package rules.summer;

import org.neslihantrpc.model.SummerSupplementEligibilityInput;
import org.neslihantrpc.enums.FamilyComposition;
import org.neslihantrpc.util.SupplementRuleUtils;
import org.neslihantrpc.enums.Supplement;

rule "Single Person With No Dependent Children AND a Household Income Less Than or Equal to $50,000 - Summer"
    when
        $input : SummerSupplementEligibilityInput(numberOfChildren == 0, familyComposition == FamilyComposition.SINGLE, householdIncome <= 50000, familyUnitInPayForJuly == true)
    then
        insert(SupplementRuleUtils.createEligibilityOutput($input, Supplement.SUMMER));
end
