package rules.winter;

import org.neslihantrpc.model.WinterSupplementEligibilityInput;
import org.neslihantrpc.model.SupplementEligibilityOutput;
import org.neslihantrpc.enums.FamilyComposition;
import org.neslihantrpc.util.SupplementRuleUtils;
import org.neslihantrpc.enums.Supplement;


rule "Childless Couple - Winter"
    when
        $input : WinterSupplementEligibilityInput(numberOfChildren == 0 , familyComposition == FamilyComposition.MARRIED ,familyUnitInPayForDecember == true)
    then
        insert(SupplementRuleUtils.createEligibilityOutput($input, Supplement.WINTER));
end

rule "Either Single Or Two Parent Family With Dependent Children - Winter"
    when
        $input : WinterSupplementEligibilityInput(numberOfChildren > 0 ,familyUnitInPayForDecember == true)
    then
        insert(SupplementRuleUtils.createEligibilityOutput($input, Supplement.WINTER));
end