package rules;

import org.neslihantrpc.model.WinterSupplementEligibilityInput;
import org.neslihantrpc.model.WinterSupplementEligibilityOutput;
import org.neslihantrpc.enums.FamilyComposition;

rule "Childless Couple"
when
    $input : WinterSupplementEligibilityInput(numberOfChildren == 0 , familyComposition == FamilyComposition.MARRIED ,familyUnitInPayForDecember == true)
then
    WinterSupplementEligibilityOutput output = new WinterSupplementEligibilityOutput();
    output.setId($input.getId());
    output.setEligible($input.getFamilyUnitInPayForDecember());
    output.setChildrenAmount($input.getNumberOfChildren());
    output.setBaseAmount(120F);
    insert(output);
end

rule "Either Single Or Two Parent Family With Dependent Children"
when
    $input : WinterSupplementEligibilityInput(numberOfChildren != 0 ,familyUnitInPayForDecember == true)
then
    WinterSupplementEligibilityOutput output = new WinterSupplementEligibilityOutput();
    output.setId($input.getId());
    output.setEligible($input.getFamilyUnitInPayForDecember());
    output.setChildrenAmount($input.getNumberOfChildren());
    output.setBaseAmount(120F);
    insert(output);
end