package rules;

import org.neslihantrpc.model.WinterSupplementEligibilityInput;
import org.neslihantrpc.model.WinterSupplementEligibilityOutput;
import org.neslihantrpc.enums.FamilyComposition;

rule "Single Person With No Dependent Children"
when
    $input : WinterSupplementEligibilityInput(numberOfChildren == 0 , familyComposition == FamilyComposition.SINGLE ,familyUnitInPayForDecember == true)
then
    WinterSupplementEligibilityOutput output = new WinterSupplementEligibilityOutput();
    output.setId($input.getId());
    output.setEligible($input.getFamilyUnitInPayForDecember());
    output.setChildrenAmount($input.getNumberOfChildren());
    output.setBaseAmount(60F);
    insert(output);
end